### ISSUE TITLE
Custom Sound samples geeting dropped

### ISSUE THREAD

**Issue by nishant2019** [ShawnHymel/tflite-speech-recognition#3]
I am trying to use the code for detection of noise and silence and have created sound samples for 10 seconds each. However all the samples gets dropped due **mfccs.shape** not being (16,16) being **Dropped: 1 (16, 196).** What can be the error ? All my samples have shape (16, 196)

**Comment by ShawnHymel** [comment]
Samples need to be exactly 1 second long, such that the MFCCs come out to be 16 chunks long.

**Comment by nishant2019** [comment]
> 
> 
> Samples need to be exactly 1 second long, such that the MFCCs come out to be 16 chunks long.

Can we go for longer time samples  ?

**Comment by ShawnHymel** [comment]
You should be able to. Try changing len_mfcc from 16 to however long your MFCCs come out to be (196). Do you need 10 seconds of data though? If you're just trying to classify noises, you probably only need 1 second. Remember that if you increase the time of each sample, you'll need to collect that much when you go to do inference, and the neural network will take much longer to compute with more dimensions.

Also, if you're just trying to detect the presence of noise vs. silence, a simple sound amplitude detector will be much easier to implement than a neural network. See here on for example code on how to do that: https://blog.yavilevich.com/2016/08/arduino-sound-level-meter-and-spectrum-analyzer/

**Comment by nishant2019** [comment]
> 
> 
> You should be able to. Try changing len_mfcc from 16 to however long your MFCCs come out to be (196). Do you need 10 seconds of data though? If you're just trying to classify noises, you probably only need 1 second. Remember that if you increase the time of each sample, you'll need to collect that much when you go to do inference, and the neural network will take much longer to compute with more dimensions.
> 
> Also, if you're just trying to detect the presence of noise vs. silence, a simple sound amplitude detector will be much easier to implement than a neural network. See here on for example code on how to do that: https://blog.yavilevich.com/2016/08/arduino-sound-level-meter-and-spectrum-analyzer/

Thanks for the guidance. Actually I looking at making something like this "https://www.researchgate.net/publication/339754525_Sign_Language_Gesture_Recognition_Using_Doppler_Radar_and_Deep_Learning". This would also be a great project for your YouTube channel. It has both IoT and Deep learning.

**Comment by ShawnHymel** [comment]
Cool project, thanks for the link! Interesting use of radar...I would have thought to use a camera to look for hands.

Closing out the issue.

**Comment by HasibAlAhmed** [comment]
Hello, can you suggest me where to change if I want this whole thing to work for 2 second input voice command?

**Comment by ShawnHymel** [comment]
@HasibAlAhmed Please open a new issue, as this one has been closed.
